#文件上传访问端口
server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  #tamcat默认2m，超过2m的文件不会被捕获


spring:
  profiles:
    active: dev #yml中配置文件的配置环境
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000 #允许最大上传文件大小为500kb
      max-request-size: 512000

  #mongodb
  data:
    mongodb:
      uri: mongodb://root:ycy@localhost:27017
      database: cloud-news
###############################
#     Fastdfds配置
#
###############################
fdfs:
  connect-timeout: 30
  so-timeout: 30
  tracker-list:  172.25.183.75:22122

