#文件上传访问端口
server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  #tamcat默认2m，超过2m的文件不会被捕获

#配置redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 111111
    database: 1

