############################################################
#
# eureka 集群的注册中心
# web访问端口号  约定：7001~7003
#
############################################################
server:
  port: ${port:7001}
  tomcat:
    uri-encoding: UTF-8

#配置项目信息
spring:
  application:
    name: springcloud-eureka-cluster

#eureka配置中心
eureka:
  instance:
    hostname: eureka-cluster-${server.port}   #eureka实例的hostname
  other-node-port2: ${p2:7002}
  other-node-port3: ${p3:7003}
  client:
    service-url:
      defaultZone: http://eureka-cluster-${eureka.other-node-port2}:${eureka.other-node-port2}/eureka/,http://eureka-cluster-${eureka.other-node-port3}:${eureka.other-node-port3}/eureka/
  server:
      enable-self-preservation: false   # 关闭eureka的自我保护功能
      eviction-interval-timer-in-ms: 5000   # 清理无效节点的时间，可以缩短为5s，默认60s


