#web访问端口
server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  #tamcat默认2m，超过2m的文件不会被捕获


spring:
  profiles:
    active: dev #yml中配置文件的配置环境
  application:
    name: service-user
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/cloud-news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root2022
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: GMT+8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: cloud-news

  cloud:
    stream:
      bindings: #绑定通道和交换机
        myOutput: #定义生产者的通道
          #自定义交换机的名字，代理构建的消息，交给底层mq交换机
          destination: streamExchange
        myInput:
          #自定义交换机的名字，消息从mq输入到消费端进行消费
          destination: streamExchange
          group: user
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web       #数据采集的通信方式web http
  sleuth:
    sampler:
      probability: 0.8    #数据采样比例0-1
 #微服务相关
eureka:
  # 自定义eureka server的信息
  server:
    hostname: localhost
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      #defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3      # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 5   # eureka 举例最近的一次心跳等待提出的时间，默认90s

######SERVER-USER开启自动以注解
#SERVER-USER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#配置Hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #设置hystrix超时时间，超过5秒自动降级
      circuitBreaker: # 配置断路器
        enabled: true
        requestVolumeThreshold: 10    # 触发熔断最小请求次数，默认：20
        sleepWindowInMilliseconds: 15000    # 熔断后过几秒后尝试半开状态（请求重试），默认：5s
        errorThresholdPercentage: 50  # 触发熔断的失败率（异常率/阈值），默认：50